# SwiftLint

reporter: "xcode"
warning_threshold: 1

disabled_rules:
  # Lint rules
  - todo
  - raw_value_for_camel_cased_codable_enum

  # Style rules
  - identifier_name
  - inclusive_language
  - indentation_width
  - multiline_function_chains
  - orphaned_doc_comment
  - trailing_comma
  - trailing_closure
  - redundant_discardable_let # #Preview macros require `let _ =` for Void-returning calls

  # Auto-correction in SwiftFormat
  # Idiomatic rules
  - redundant_type_annotation
  - strict_fileprivate
  - unavailable_function
  # Lint rules
  - comment_spacing
  # Style rules
  - implicit_return
  - modifier_order
  - sorted_imports

opt_in_rules:
  # Idiomatic rules
  - block_based_kvo
  - convenience_type
  - discouraged_object_literal
  - discouraged_optional_boolean
  - duplicate_imports
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - for_where
  - force_cast
  - force_try
  - force_unwrapping
  - generic_type_name
  - implicitly_unwrapped_optional
  - is_disjoint
  - joined_default_parameter
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_multiple
  - legacy_nsgeometry_functions
  - legacy_random
  - no_fallthrough_only
  - pattern_matching_keywords
  - prefer_zero_over_explicit_init
  - private_over_fileprivate
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - implicit_optional_initialization
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_void_return
  - static_operator
  - syntactic_sugar
  - toggle_bool
  - trailing_semicolon
  - type_name
  - unneeded_break_in_switch
  - untyped_error_in_catch
  - unused_enumerated
  - xct_specific_matcher
  - xctfail_message

  # Lint rules
  - array_init
  - class_delegate_protocol
  - compiler_protocol_init
  - deployment_target
  - discarded_notification_center_observer
  - discouraged_direct_init
  - duplicate_enum_cases
  - dynamic_inline
  - empty_xctest_method
  - expiring_todo
  - ibinspectable_in_extension
  - identical_operands
  - mark
  - multiline_arguments
  - notification_center_detachment
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - nsobject_prefer_isequal
  - overridden_super_call
  - override_in_extension
  - private_action
  - private_outlet
  - private_unit_test
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - required_enum_case
  - strong_iboutlet
  - superfluous_disable_command
  - test_case_accessibility
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_setter_value
  - valid_ibinspectable
  - weak_delegate
  - yoda_condition

  # Metrics rules
  - closure_body_length
  - enum_case_associated_values_count
  - large_tuple
  - nesting
  - type_body_length

  # Performance rules
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - first_where
  - flatmap_over_map_reduce
  - last_where
  - reduce_boolean
  - reduce_into
  - sorted_first_last

  # Style rules
  - closing_brace
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - computed_accessors_order
  - control_statement
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - implicit_getter
  - leading_whitespace
  - literal_expression_end_indentation
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - multiple_closures_with_trailing_closure
  - no_space_in_method_call
  - number_separator
  - opening_brace
  - operator_usage_whitespace
  - function_name_whitespace
  - optional_enum_case_matching
  - prefer_self_type_over_type_of_self
  - protocol_property_accessors_order
  - return_arrow_whitespace
  - shorthand_operator
  - single_test_class
  - statement_position
  - switch_case_alignment
  - switch_case_on_newline
  - trailing_newline
  - trailing_whitespace
  - unowned_variable_capture
  - unneeded_parentheses_in_closure_argument
  - unused_optional_binding
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - void_return

analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import

included:
  - EmpUI_iOS/
  - EmpUI_macOS/
  - EmpDesignSystem/

excluded:
  - Tuist/
  - Derived/

# Rules configuration

# Idiomatic rules configuration
private_over_fileprivate:
  validate_extensions: true
type_name:
  max_length:
    warning: 56

# Metrics rules configuration
file_length:
  warning: 400
  error: 500
  ignore_comment_only_lines: true
function_parameter_count:
  warning: 7
function_body_length:
  warning: 60
  error: 120
large_tuple:
  warning: 5
  error: 6
line_length:
  warning: 140
  error: 140
  ignores_comments: true
  ignores_function_declarations: false
  ignores_interpolated_strings: true
  ignores_urls: true
nesting:
  always_allow_one_type_in_functions: true
  type_level:
    warning: 2
type_body_length:
  warning: 300
  error: 500

# Performance rules configuration
contains_over_filter_count:
  severity: error
contains_over_filter_is_empty:
  severity: error
contains_over_first_not_nil:
  severity: error
contains_over_range_nil_comparison:
  severity: error
empty_collection_literal:
  severity: error
empty_count:
  severity: error
empty_string:
  severity: error
first_where:
  severity: error
flatmap_over_map_reduce:
  severity: error
last_where:
  severity: error
reduce_boolean:
  severity: error
reduce_into:
  severity: error
sorted_first_last:
  severity: error
